/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as DashboardIdRouteImport } from './routes/dashboard.$id'
import { Route as DashboardMobileIdRouteImport } from './routes/dashboard.mobile.$id'

const IndexLazyRouteImport = createFileRoute('/')()
const ProjectsIndexLazyRouteImport = createFileRoute('/projects/')()

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProjectsIndexLazyRoute = ProjectsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any).lazy(() =>
  import('./routes/projects.index.lazy').then((d) => d.Route),
)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const DashboardIdRoute = DashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMobileIdRoute = DashboardMobileIdRouteImport.update({
  id: '/dashboard/mobile/$id',
  path: '/dashboard/mobile/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/dashboard/mobile/$id': typeof DashboardMobileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/dashboard/$id': typeof DashboardIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexLazyRoute
  '/dashboard/mobile/$id': typeof DashboardMobileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/dashboard/$id': typeof DashboardIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexLazyRoute
  '/dashboard/mobile/$id': typeof DashboardMobileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/dashboard/$id'
    | '/projects/$id'
    | '/projects/'
    | '/dashboard/mobile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/$id'
    | '/projects/$id'
    | '/projects'
    | '/dashboard/mobile/$id'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/dashboard/$id'
    | '/projects/$id'
    | '/projects/'
    | '/dashboard/mobile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  DashboardIdRoute: typeof DashboardIdRoute
  DashboardMobileIdRoute: typeof DashboardMobileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexLazyRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/dashboard/$id': {
      id: '/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof DashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mobile/$id': {
      id: '/dashboard/mobile/$id'
      path: '/dashboard/mobile/$id'
      fullPath: '/dashboard/mobile/$id'
      preLoaderRoute: typeof DashboardMobileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexLazyRoute: typeof ProjectsIndexLazyRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexLazyRoute: ProjectsIndexLazyRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  DashboardIdRoute: DashboardIdRoute,
  DashboardMobileIdRoute: DashboardMobileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
